
##############################permutates species to test whether some clades have more htt than expected by chance. This can be run at any point after step 12.
source('HTvFunctions.R')
tree = read.tree("timetree.nwk")
retainedHits = fread("supplementary-data4-retained_hits")		#data file provided with the paper, which is a table of hits representing HTT


#sbatch --mail-type=BEGIN,END,FAIL --cpus-per-task=20 --mem=20G --wrap="Rscript randomSpeciesPairs.R 20"		#performs the permutations on 20 CPUs

#counting the number of HTT per taxa in real and randomised hits.
randomHTTs = readRDS("allPermutations_Node.308.RDS")		#results of permutations generated by randomSpeciesPairs.R (= pairs of species representing real and simulated HTT)

taxa = fread("namedClades.txt")
sps = tipsForNodes(tree, taxa[onPlot == T,node])			#obtains the species (tip numbers in the tree) composing each taxon that will be shown on the figure
taxon = sps[,node[order(tip)]]								#so for each species (index of this vector), we have the taxon (tree node)

countHTTs = function(superfamily) {							#counts htt per taxon in a given TE super family (or batch within a larger superfamily) to obtain stats (mean, quantiles) for simulated transfers
	unFolded = randomHTTs[[superfamily]][,.(sp = c(sp1, sp2), repl = c(repl, repl))]		#we "unfold" the species pairs in htts, separating species 1 and 2, duplicating HTTs. Effectively, if a hit involves 2 species of the same taxon, two HTTs will be counted for the taxon
	unFolded[,taxon := taxon[sp]]	
	counts = unFolded[,.(N =.N/2), by = .(taxon, repl)]				#counts numbers of transfers involving each taxon in each replicate (note that repl == 0 for real HTT events)	
	nRepl = max(randomHTTs[[superfamily]]$repl)
	uTaxa = unique(taxon)
	missingTaxa = data.table(taxon = rep(uTaxa, nRepl), repl = rep(1:nRepl, each = length(uTaxa)), N = 0)		#this table is required to add 0 counts for taxa not involved in HTT in each replicate since they are simply missing (if we didn't do this, the stats would be biased upwards)
	counts = rbind(counts, missingTaxa)			
	counts = counts[!duplicated(data.table(taxon, repl))]				#of course, we remove 0 counts for taxa present in the replicates
	stats = counts[repl > 0L,.(simulated = mean(N), minNumber = min(N), maxNumber = max(N),  qLc = quantile(N, 0.005), qRc = quantile(N, 0.995), qL5 = quantile(N, 0.025), qR5 = quantile(N, 0.975), superfamily), by = taxon]		#obtains the statistics over permutations for simulated data
	merge(stats,  counts[repl == 0L,.(taxon, observed = N)], by ="taxon", all = T)			#adding number of real number of HTT events to the results
}


stats = lapply(names(randomHTTs), countHTTs)				#obtaining HTT counts on real an randomized data for all super families
stats = rbindlist(stats)
stats[is.na(observed), observed := 0]						#the merge in the function above creates NA for taxa not involved in real transfers
stats[,class := ifelse(grepl("CMC|hAT|Mariner|Maverick|Merlin|PIF|PiggyBac|DNA", superfamily),"DNA","RNA")]		#attributes TE class (note that many of these families are not even in the table, but they could in other situations)

#contrasting randomized and observed HTT numbers of the different taxa we selected and for each TE class
statsPerClass = stats[,.(simulated = sum(simulated), minNumber = sum(minNumber), maxNumber = sum(maxNumber), qLc = sum(qLc), qRc = sum(qRc), qL5 = sum(qL5), qR5 = sum(qR5), observed = sum(observed)), by = .(class, taxon)]	
sumSimulated = statsPerClass[,sum(simulated),by = .(node = taxon)]			#counts the number of simulated HTT per taxon, to put the taxa the most involved on top 
statsPerClass = statsPerClass[order(sumSimulated[match(taxon,node), -V1], class),]

#building the connected barplots (figure 3)
statsPerClass[,col := taxa[match(taxon, node), col]]		#taxa-specific color used for the plots, the same as on figure 2

linkedPlots = function(dt, space = 2, legend = F,...) {		#generates the linked barplot figure. Almost all the code adds stars for siginificance levels
	b = dt[,linkedBarPlot(cbind(simulated, observed), col = col, junCol = fadeTo(col, "black", 0.4), space = space, main = ifelse(class[1] =="DNA", "DNA transposons","Retrotransposons"), border = grey(0.3),...)]
	dt[, stars := ""]										#no star by default
	dt[observed < qL5 | observed > qR5, stars := "*"]		#difference at the 5% level
	dt[observed < qLc | observed > qRc, stars := "**"]		#at the 1% level
	dt[observed < minNumber | observed > maxNumber, stars := "***"]  	#at the 1/1000 level
	f = dt$stars != ""			#TRUE when there are significant differences
	labels = dt[f,] 
	y = cumsum(c(0, dt$observed))			#below, we compute the location of the stars, and the segments linking them to the barplot sections. This can be tricky for small barplot sectors, as we need to avoid collisions. 
	mids = (y[which(f)] + y[which(f)+1L]) /2
	yPos = c(0,mids) 
	for(i in 2:length(yPos)) {
		delta = yPos[i] - yPos[i-1L]
		if(delta < 15) yPos[i] = yPos[i] + 15 - delta
	}
	yPos = c(yPos[-1], sum(dt$observed))
	for(i in length(yPos):2) {
		delta = yPos[i] - yPos[i-1L]
		if(delta < 15) yPos[i-1L] = yPos[i-1L] - 15 + delta
	}
	yPos = yPos[-length(yPos)]
	t = labels[,text(2*space + 2.55, yPos, stri_c(round(observed/simulated, 2),stars), adj = c(0, 0.5))]
	segments(2*space + 2, mids, 2*space + 2.5, yPos, col = dt$col[f], lwd = 1)
	if(legend) 	legend(x = 2*space + 3.5, y = sum(dt$observed), legend = rev(taxa[match(dt$taxon, node), name]), bty = "n", fill = rev(dt$col), border = grey(0.3))
}

pdf(file = "figure3.pdf", width = 8, height = 4.5)
layout(cbind(1, 2, 3), widths = c(1, 1, 0.4))			#the rightmost section is there for the legend only
par(lwd = 0.5, xpd = NA, las = 1, mai = c(0.6, 0.55, 0.55, 0.6))
linkedPlots(statsPerClass[class =="DNA"], ylab ="number of transfers")
linkedPlots(statsPerClass[class =="RNA"], legend = T)
dev.off()

#for ray-finned fishes, we record results for each super family (table S1)
rayFin = stats[taxon == 312L,.(mean_over_simulations = round(sum(simulated),2), max_over_simulations = sum(maxNumber), observed = sum(observed)), by = testSplit(superfamily, ".", 1)]
writeT(rayFin, "tableS1.txt")


############### investigating if more transfers between "fishes" and tetrapods involved aquatic tetrapods
# we first create a list indicating the main habitat of the species (species are tip numbers on the timetree)
tetrapods = tipsForNode(tree, 375)				
aquatic = c(tipsForNodes(tree, c(376, 472, 474, 514, 501, 463))$tip, grep("Trichechus", tree$tip.label))	#aquatic species among tetrapods
fishes = setdiff(1:length(tree$tip.label), tetrapods)						#fishes as a paraphyletic group (non-tretrapods)

habitatEffect = function(tetrapods, aquatic) {					#this permutates tetrapod species among the tetrapod-fish HTT. This is fast since this cannot general illegal HTTs (the randomized hit will still be between fishes and tetrapods)
	tetraHits = HTThits[(sp1 %in% tetrapods & sp2 %in% fishes) | (sp2 %in% tetrapods & sp1 %in% fishes)]		#hits between a tetrapod and a non-tetrapod
	tetraHits[!sp1 %in% tetrapods, c("sp1","sp2") := .(sp2, sp1)]			#always puts the tetrapod species on the left
	tetraHits[, sp1 := match(sp1, tetrapods)]					#renumbers the tetrapod species to help the simulation
	
	aquatic = match(aquatic, tetrapods) ; l = length(tetrapods)
	permu = replicate(10000, sample(l))
	sp1 = tetraHits$sp1 + rep(1:10000-1L, each = nrow(tetraHits))*l
	sp1 = permu[sp1]
	pairs = rbind(data.table(sp1 = tetraHits$sp1, repl = 0L), data.table(sp1, repl = rep(1:10000, each = nrow(tetraHits))))
	pairs[,habitat := "land"] ; pairs[sp1 %in% aquatic, habitat := "water"]
	perPerm = pairs[repl > 0L, .N, by = .(repl, habitat)]
	simu = perPerm[,.(mean = mean(N), q1 = quantile(N, 1/1000), q999 = quantile(N, 999/1000)), by = habitat]
	real = pairs[repl == 0L, .(observed =.N), by = habitat]
	merge(simu, real, by = "habitat")
}

habitatEffect(tetrapods, aquatic)

#### same, but only within birds and mammals
#### to increase power, we use all hit groups, not just the "independent" ones
HTThits = retainedHits[!duplicated(hitgroup), data.table(sp1 = chmatch(sp1, tree$tip.label), sp2 = chmatch(sp2, tree$tip.label))]

birdsMams = tipsForNodes(tree, c(477, 391))$tip
aquaticBM = intersect(aquatic, birdsMams)
habitatEffect(birdsMams, aquaticBM)

#### same, but ignoring birds and mammals
nonBirdsMams = setdiff(tetrapods, birdsMams)
aquaticNBM = setdiff(aquatic, birdsMams)
habitatEffect(nonBirdsMams, aquaticNBM)
