##%######################################################%##
#                                                          #
####  This stages blasts TE copies against the databse  ####
#### of repeat proteins to find protein regions in TEs. ####
#                                                          #
##%######################################################%##


#As a single copy may encompass several proteins (in particular, for
#retrotransposons), we blast copies once to retain only the best hit per copy,
#then we extract TE parts that are not in HSPs, and blast them again. Five
#"rounds" of blast searches are performed. We do that rather than retrieving
#many hits per TE in a single blast because this gives not garanty to find all
#the porteins of the TE (most of the hits would be likely to inolve the same TE
#region that aligns on homologous proteins of repbase).

source("HTvFunctions.R")
args = commandArgs(trailingOnly = TRUE)
nCPUs = as.integer(args[1])
setwd("TEs")

outFolder = "blastx/out/"
doneFolder = "blastx/done/"
dir.create(doneFolder, recursive = T)
dir.create(outFolder)


beds = list.files("selectedCopies", pattern = ".txt", full.names = T)	#bed files of TE copy (or copy parts) to extract from TE fastas (with seqtk), generated by 7-TEKsAndHTTfilter.R
sp = unique(extractSpeciesNames(beds))
done = stri_c(doneFolder, sp, ".copies.successiveBlastX.out")	#generates output file names of finished searches
f = !file.exists(done)											#in case the job needs to be relaunched, avoids redoing searches that were already done
sp = sp[f]
done = done[f]

db = ("findDubious/repeatPeps.dmnd")							#database or repeat proteins generated at step 3-findDubiousTEs.R
successiveBlastx  = function(sp, done, maxRounds) {
  #does the blastx searches for a given species. maxRounds will be 5
  fas = stri_c("copies/", sp, ".TEs.fasta.gz")
  bed = stri_c("selectedCopies/", sp, ".txt")
  combined = data.table()										#will contains the combined hits of the successive blasts
  for (round in 1:maxRounds) {
    out = stri_c(outFolder, sp, ".", round, ".out")			#generates output file name of current search
    blast = seqtkDiamond(fas, bed, db, out)								#this extracts TEs (or TE parts) with seqtk and pipes them to diamond blastx
    if (nrow(blast) == 0)
      break
    combined = rbind(combined, processBlastX(blast))					#combines the current hits with any previous ones and processing the output (see processBlastX() function)
    if (round < maxRounds) {
      parts = unalignedParts(combined)								#extract TE parts not involved in hits (a bed-like table)
      if (nrow(parts) == 0)
        break
      bed = stri_c("selectedCopies/", sp, ".", round, ".bed")			#creates a bed file for these parts
      writeT(parts, bed, col.names = F)
    } 																	#and repeats
  }
  writeT(combined, done, col.names = F)						#writes output to the done/ folder once finished
  return(NULL)
}

m = mcMap(successiveBlastx,
          sp,
          done,
          5,
          mc.cores = nCPUs,
          mc.preschedule = F)		#performed in parallel for several species
system("cat blastx/done/*.out > blastx/all.copies.successiveBlastx.out")
system("cat blastx/out/*.out > blastx/allRaw.out")		#
